import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import '../../data/database/app_database.dart';
import '../../data/repositories/analysis_repository.dart';
import '../../config/theme.dart';

class AnalysisDetailScreen extends ConsumerStatefulWidget {
  const AnalysisDetailScreen({super.key, required this.analysisId});

  final int analysisId;

  @override
  ConsumerState<AnalysisDetailScreen> createState() =>
      _AnalysisDetailScreenState();
}

class _AnalysisDetailScreenState extends ConsumerState<AnalysisDetailScreen> {
  AnalysisResultData? _analysis;
  bool _isLoading = true;
  String? _error;

  @override
  void initState() {
    super.initState();
    _loadAnalysis();
  }

  Future<void> _loadAnalysis() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });
    try {
      final repo = ref.read(analysisRepositoryProvider);
      final result = await repo.getById(widget.analysisId);
      setState(() {
        _analysis = result;
        _isLoading = false;
      });
      if (result == null) {
        setState(() => _error = 'Analysis not found');
      }
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Color _gainLossColor(BuildContext context, double change) {
    final colors = Theme.of(context).extension<StockColors>() ??
        const StockColors(gainColor: Colors.green, lossColor: Colors.red);
    return change >= 0 ? colors.gainColor : colors.lossColor;
  }

  void _share() {
    if (_analysis == null) return;
    final a = _analysis!;
    final text = '''
AI Stock Prediction Analysis: ${a.symbol}

Current Price: \$${a.currentPrice.toStringAsFixed(2)}
Predicted Price: \$${a.predictedPrice.toStringAsFixed(2)}
Confidence: ${(a.confidence * 100).toStringAsFixed(0)}%
Recommendation: ${a.recommendation}
Timeframe: ${a.timeframe}

${a.reasoning}

${a.newsSummary.isNotEmpty ? 'News Summary:\n${a.newsSummary}' : ''}

Generated by AI Stock Prediction App
''';
    Share.share(text, subject: 'AI Analysis: ${a.symbol}');
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Analysis')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    if (_error != null || _analysis == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Analysis')),
        body: Center(child: Text(_error ?? 'Not found')),
      );
    }

    final a = _analysis!;
    final price = a.currentPrice;
    final predicted = a.predictedPrice;
    final change = predicted - price;
    final changePct = price != 0 ? (change / price) * 100 : 0.0;
    final isPositive = change >= 0;
    final color = _gainLossColor(context, change);
    final confidence = a.confidence.clamp(0.0, 1.0);
    final confidenceColor = confidence >= 0.7
        ? Colors.green
        : confidence >= 0.4
            ? Colors.amber
            : Colors.red;

    final dateStr = '${a.createdAt.year}-${a.createdAt.month.toString().padLeft(2, '0')}-${a.createdAt.day.toString().padLeft(2, '0')}';

    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(a.symbol),
            if (dateStr.isNotEmpty)
              Text(dateStr, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.normal)),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _share,
            tooltip: 'Share',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text('\$${predicted.toStringAsFixed(2)}',
                        style: Theme.of(context).textTheme.headlineLarge?.copyWith(fontWeight: FontWeight.bold)),
                    const SizedBox(width: 12),
                    Padding(
                      padding: const EdgeInsets.only(bottom: 4),
                      child: Row(
                        children: [
                          Icon(isPositive ? Icons.arrow_upward : Icons.arrow_downward, color: color, size: 18),
                          Text('${isPositive ? "+" : ""}${change.toStringAsFixed(2)} (${isPositive ? "+" : ""}${changePct.toStringAsFixed(2)}%)',
                              style: TextStyle(color: color, fontWeight: FontWeight.w600, fontSize: 15)),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Text('Confidence: ${(confidence * 100).toStringAsFixed(0)}%',
                    style: const TextStyle(fontWeight: FontWeight.w600)),
                const SizedBox(height: 4),
                ClipRRect(
                  borderRadius: BorderRadius.circular(4),
                  child: LinearProgressIndicator(value: confidence, color: confidenceColor, minHeight: 8),
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                      decoration: BoxDecoration(
                        color: switch (a.recommendation) {
                          'BUY' => Colors.green,
                          'SELL' => Colors.red,
                          _ => Colors.amber,
                        }.withValues(alpha: 0.2),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(a.recommendation,
                          style: TextStyle(
                            color: switch (a.recommendation) {
                              'BUY' => Colors.green.shade700,
                              'SELL' => Colors.red.shade700,
                              _ => Colors.amber.shade800,
                            },
                            fontWeight: FontWeight.bold,
                          )),
                    ),
                    const SizedBox(width: 8),
                    Text(a.timeframe, style: const TextStyle(fontSize: 12)),
                  ],
                ),
                const SizedBox(height: 16),
                Text('Current Price: \$${price.toStringAsFixed(2)}',
                    style: Theme.of(context).textTheme.bodyMedium),
                const SizedBox(height: 16),
                Text('AI Reasoning', style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                const SizedBox(height: 8),
                Text(a.reasoning, style: const TextStyle(fontSize: 14, height: 1.4)),
                if (a.newsSummary.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('News Summary', style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Text(a.newsSummary, style: const TextStyle(fontSize: 14, height: 1.4)),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}
