import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import '../../data/database/app_database.dart';
import '../../data/repositories/analysis_repository.dart';
import '../../config/theme.dart';
import '../../engine/staleness_tracker.dart';

class AnalysisDetailScreen extends ConsumerStatefulWidget {
  const AnalysisDetailScreen({super.key, required this.analysisId});

  final int analysisId;

  @override
  ConsumerState<AnalysisDetailScreen> createState() =>
      _AnalysisDetailScreenState();
}

class _AnalysisDetailScreenState extends ConsumerState<AnalysisDetailScreen> {
  AnalysisResultData? _analysis;
  bool _isLoading = true;
  String? _error;

  @override
  void initState() {
    super.initState();
    _loadAnalysis();
  }

  Future<void> _loadAnalysis() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });
    try {
      final repo = ref.read(analysisRepositoryProvider);
      final result = await repo.getById(widget.analysisId);
      setState(() {
        _analysis = result;
        _isLoading = false;
      });
      if (result == null) {
        setState(() => _error = 'Analysis not found');
      }
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Color _gainLossColor(BuildContext context, double change) {
    final colors = Theme.of(context).extension<StockColors>() ??
        const StockColors(gainColor: Colors.green, lossColor: Colors.red);
    return change >= 0 ? colors.gainColor : colors.lossColor;
  }

  void _share() {
    if (_analysis == null) return;
    final a = _analysis!;
    final text = '''
AI Stock Prediction Analysis: ${a.symbol}

Current Price: \$${a.currentPrice.toStringAsFixed(2)}
Predicted Price: \$${a.predictedPrice.toStringAsFixed(2)}
Confidence: ${(a.confidence * 100).toStringAsFixed(0)}%
Recommendation: ${a.recommendation}
Timeframe: ${a.timeframe}

${a.reasoning}

${a.newsSummary.isNotEmpty ? 'News Summary:\n${a.newsSummary}' : ''}

Generated by AI Stock Prediction App
''';
    Share.share(text, subject: 'AI Analysis: ${a.symbol}');
  }

  Color _signalColor(String signal) {
    switch (signal) {
      case 'Opportunity':
      case 'BUY':
        return Colors.green.shade700;
      case 'Caution':
      case 'SELL':
        return Colors.red.shade700;
      default:
        return Colors.amber.shade800;
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Analysis')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    if (_error != null || _analysis == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Analysis')),
        body: Center(child: Text(_error ?? 'Not found')),
      );
    }

    final a = _analysis!;
    final price = a.currentPrice;
    final predicted = a.predictedPrice;
    final change = predicted - price;
    final changePct = price != 0 ? (change / price) * 100 : 0.0;
    final isPositive = change >= 0;
    final color = _gainLossColor(context, change);
    final confidence = a.confidence.clamp(0.0, 1.0);
    final confidenceColor = confidence >= 0.7
        ? Colors.green
        : confidence >= 0.4
            ? Colors.amber
            : Colors.red;

    final staleness = StalenessTracker().enrichAnalysis({
      'created_at': a.createdAt,
      'confidence': confidence * 100,
    });
    final stalenessLevel = staleness['staleness_level'] as String;
    final decayedConf = staleness['decayed_confidence'] as double;

    final dateStr = '${a.createdAt.year}-${a.createdAt.month.toString().padLeft(2, '0')}-${a.createdAt.day.toString().padLeft(2, '0')}';

    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(a.symbol),
            if (dateStr.isNotEmpty)
              Text(dateStr, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.normal)),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _share,
            tooltip: 'Share',
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text('\$${predicted.toStringAsFixed(2)}',
                        style: Theme.of(context).textTheme.headlineLarge?.copyWith(fontWeight: FontWeight.bold)),
                    const SizedBox(width: 12),
                    Padding(
                      padding: const EdgeInsets.only(bottom: 4),
                      child: Row(
                        children: [
                          Icon(isPositive ? Icons.arrow_upward : Icons.arrow_downward, color: color, size: 18),
                          Text('${isPositive ? "+" : ""}${change.toStringAsFixed(2)} (${isPositive ? "+" : ""}${changePct.toStringAsFixed(2)}%)',
                              style: TextStyle(color: color, fontWeight: FontWeight.w600, fontSize: 15)),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Text('Confidence: ${(confidence * 100).toStringAsFixed(0)}%',
                    style: const TextStyle(fontWeight: FontWeight.w600)),
                const SizedBox(height: 4),
                ClipRRect(
                  borderRadius: BorderRadius.circular(4),
                  child: LinearProgressIndicator(value: confidence, color: confidenceColor, minHeight: 8),
                ),
                if (staleness['age_days'] as int > 0) ...[
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      Icon(
                        stalenessLevel == 'fresh' || stalenessLevel == 'recent'
                            ? Icons.schedule
                            : Icons.warning_amber,
                        size: 16,
                        color: stalenessLevel.contains('stale')
                            ? Colors.orange
                            : Colors.grey,
                      ),
                      const SizedBox(width: 6),
                      Expanded(
                        child: Text(
                          '${staleness['staleness_label']} (${staleness['age_days']}d) · '
                          'Decayed confidence ${decayedConf.toStringAsFixed(0)}%',
                          style: TextStyle(
                            fontSize: 12,
                            color: staleness['needs_refresh'] == true
                                ? Colors.orange.shade800
                                : null,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
                const SizedBox(height: 12),
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                      decoration: BoxDecoration(
                        color: _signalColor(a.signal).withValues(alpha: 0.2),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        a.signal.isNotEmpty ? a.signal : a.recommendation,
                        style: TextStyle(
                          color: _signalColor(a.signal),
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    if (a.quantScore != null)
                      Text('Quant ${a.quantScore}/100',
                          style: const TextStyle(fontSize: 12)),
                    const SizedBox(width: 8),
                    Text('Risk ${a.riskScore}/10',
                        style: const TextStyle(fontSize: 12)),
                    if (a.geoRiskScore != null) ...[
                      const SizedBox(width: 8),
                      Text('Geo ${a.geoRiskScore}/10',
                          style: const TextStyle(fontSize: 12)),
                    ],
                  ],
                ),
                if (a.bullCase.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('Bull Case',
                      style: Theme.of(context)
                          .textTheme
                          .titleSmall
                          ?.copyWith(fontWeight: FontWeight.bold, color: Colors.green.shade700)),
                  const SizedBox(height: 8),
                  Text(a.bullCase, style: const TextStyle(fontSize: 14, height: 1.4)),
                ],
                if (a.bearCase.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('Bear Case',
                      style: Theme.of(context)
                          .textTheme
                          .titleSmall
                          ?.copyWith(fontWeight: FontWeight.bold, color: Colors.red.shade700)),
                  const SizedBox(height: 8),
                  Text(a.bearCase, style: const TextStyle(fontSize: 14, height: 1.4)),
                ],
                if (a.fundamental.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('Fundamentals',
                      style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Text(a.fundamental, style: const TextStyle(fontSize: 13, height: 1.4)),
                ],
                if (a.technical.isNotEmpty) ...[
                  const SizedBox(height: 12),
                  Text('Technicals',
                      style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Text(a.technical, style: const TextStyle(fontSize: 13, height: 1.4)),
                ],
                const SizedBox(height: 16),
                Text('Summary / Reasoning',
                    style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                const SizedBox(height: 8),
                Text(a.reasoning, style: const TextStyle(fontSize: 14, height: 1.4)),
                if (a.newsSummary.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('News Summary',
                      style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Text(a.newsSummary, style: const TextStyle(fontSize: 14, height: 1.4)),
                ],
                if (a.sources.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text('Sources',
                      style: Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Text(a.sources, style: const TextStyle(fontSize: 13, height: 1.4)),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}
